Document: yanshee-depends
Title: Debian yanshee-depends Manual
Author: <insert document author here>
Abstract: This manual describes what yanshee-depends is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yanshee-depends/yanshee-depends.sgml.gz

Format: postscript
Files: /usr/share/doc/yanshee-depends/yanshee-depends.ps.gz

Format: text
Files: /usr/share/doc/yanshee-depends/yanshee-depends.text.gz

Format: HTML
Index: /usr/share/doc/yanshee-depends/html/index.html
Files: /usr/share/doc/yanshee-depends/html/*.html
